name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/razee-engine:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/}/razee-engine:latest:latest

      - name: Deploy to DigitalOcean
        env:
          DO_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no root@your_droplet_ip "
            cd /path/to/your/deployments
            git pull origin main
            docker-compose pull
            docker-compose up -d
          "
